# Generated by Django 5.0.4 on 2024-04-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_amount_user',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
